#
# docker stack deploy -c devel.yml cam
#
version: '3.6'
services:
  portal:
    restart: always
    image: docker.homejota.net/node14-ffmpeg
    ports:
        - 8079:8079/tcp # Web Server
        - 9222:9222/tcp # Debugger
    working_dir: /usr/src/app
    volumes:
        - ./..:/usr/src/app
        - .:/home/config
        - /Volumes/fotos/ftp:/data
    command: "npm run-script debug"
    #command: "npm run-script start"
